### ISSUE TITLE
Font misalignment in converted pdf 

### ISSUE THREAD

**Issue by rajasuba** [ricn/kristin#10]
**FONT ISSUES WITH PDF TO HTML CONVERSION**
-------------------------------------------------------------------------------------------------------------------------------------------

**1.All "ti","fi","tt" characters are missing**
------------------------------------------------------------------------------------------------------------------------

SAMPLE SCREENSHOT

<img width="515" alt="screen shot 2016-04-25 at 4 13 44 pm" src="https://cloud.githubusercontent.com/assets/7858534/14781540/b8f02d7c-0b00-11e6-8435-b788a3b61678.png">

**2. Font overlapping issue**
------------------------------------------------------------------------------------------------------------------------

SAMPLE SCREENSHOT

<img width="712" alt="screen shot 2016-04-25 at 4 16 07 pm" src="https://cloud.githubusercontent.com/assets/7858534/14781585/0d554b7c-0b01-11e6-85ce-a0afb475b283.png">

- _NOTE: I don't get this issue with firefox. Getting the above issues in chrome in safari browser_

**I AM USING**
------------------------------------------------------------------------------------------------------------------------

- Using the **0.13.6** version of pdf2htmlEX 
- Using the following command to convert pdf to html

> **pdf2htmlEX --split-pages 1 --zoom 3 --fit-width 920 --correct-text-visibility 1 --dest-dir $1 $2 2>&1**

**TRIED WITH**
------------------------------------------------------------------------------------------------------------------------

Using **--fallback 1** option solves all my above problems. But 

1. The fallback option reduces the clear visiblilty. Please refer the below screen shots.

SCREENSHOT WITH FALLBACK ENABLED

<img width="809" alt="screen shot 2016-04-25 at 4 21 20 pm" src="https://cloud.githubusercontent.com/assets/7858534/14781729/e450dcae-0b01-11e6-865e-830090ef3c42.png">

SCREENSHOT WITH FALLBACK DISABLED

<img width="800" alt="screen shot 2016-04-25 at 4 22 07 pm" src="https://cloud.githubusercontent.com/assets/7858534/14781728/e4496924-0b01-11e6-960c-ed71b9180ee7.png">

2.Table in the page disappears rather replaced with empty space.

**PLEASE CLARIFY**
------------------------------------------------------------------------------------------------------------------------

1. Could you explain a bit more on fallback?

2. I have tried the above one (using fallback). Please suggest me if you prefer a different approach.

Kindly help me in this regard.

**Comment by ricn** [comment]
You have to post this issue on https://github.com/coolwanglu/pdf2htmlEX. This is just a simple wrapper for pdf2htmlex written in Ruby.
