### ISSUE TITLE
How much max size of pdf we can convert to html? 

### ISSUE THREAD

**Issue by satendra-dhillon** [ricn/kristin#6]
Hi, 

I am trying to convert the pdf in MB, but it is unable to convert it to the Html. 
Is there is any way to convert the large size(upto 10 MBs ) of pdf to html.

**Comment by ricn** [comment]
There's no upper limit on the file size. 10 MB should work just fine. Try converting the pdf manually with the pdf2htmlex command line and see if you get any errors.
